apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: shcherbatyy/authservice:test
          env:
            - name: ConnectionStrings__DefaultConnection
              value: Host=postgres-clusterip-srv;Port=5432;Database=AuthDb;Username=postgres;Password=pa55wOrd
            - name: AppSettings__Secret
              value: THIS IS MINE TO SIGN AND VERIFY JWT TOKENS, REPLACE IT WITH YOUR OWN SECRET, IT CAN BE ANY STRING
            - name: AppSettings__RefreshTokenTTL
              value: "50"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auth-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: authservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80